---
title: "NOAA Dataset from National Climatic Data Center"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
knitr::opts_chunk$set(echo = TRUE)
library(viridis)
library(p8105.datasets)
library(plotly)
library(tidyverse)
library(rnoaa)
library(dplyr)
library(lubridate)
library(gganimate)
library(gifski)
library(p8105.datasets)
library(fmsb)
library(RColorBrewer)
library(scales)


# Load the data
load("./nynoaadat.RData")

daily_tmin_tmax = 
  nydat %>% 
  mutate(date = as.character(date)) %>% 
  group_by(date) %>% 
  mutate(
    avg_tmax = mean(tmax, na.rm = TRUE),
    avg_tmin = mean(tmin, na.rm = TRUE)
    ) %>% 
  select(date, avg_tmax, avg_tmin) %>% 
  unique() %>%
  mutate(
    diff_max_min = avg_tmax - avg_tmin,
    month = substr(date, 6, 7),
    year = substr(date, 1, 4)
    )

```

Column {data-width=750}
-----------------------------------------------------------------------

### Chart A

```{r heat_max_temp, echo = FALSE, warning = FALSE, out.width="90%" }
heatmap_794 = 
  nydat %>% 
  filter(id == "USW00094794") %>% 
  mutate(year = year(date),
         month = month(date, label = TRUE),
         day = day(date)) %>% 
  filter(year %in% c(1986, 1996, 2006)) %>% 
  select(id, day, month, year, tmax) %>%
  ggplot(
    aes(
      x = month,
      y = day,
      fill = tmax
    )
  )+
  geom_tile(
    color = "white",
    size = 0.1
  )+
  ggtitle("The maximum temperature pattern in 1986, 1996, 2006")+
  scale_y_continuous(breaks =c(1,10,20,31))+
  scale_fill_viridis(name = "Maximum Temperature", option = "C")+
  facet_grid(~year)+
  labs( x="Month", y="Day Commencing")+ 
  theme(legend.position = "bottom")+
  theme(plot.title=element_text(size = 14))+
  theme(axis.text.y=element_text(size=6)) +
  theme(strip.background = element_rect(colour="white"))+
  theme(plot.title=element_text(hjust=0))+
  theme(axis.ticks=element_blank())+
  theme(axis.text=element_text(size=7))+
  theme(legend.title=element_text(size=8))+
  theme(legend.text=element_text(size=6))+
  theme_linedraw()

ggplotly(heatmap_794)

```


Column {data-width=350}
-----------------------------------------------------------------------


### Chart B

```{r box_temp_diff, echo = FALSE, warning= FALSE}
boxplot_diff = 
  daily_tmin_tmax %>% 
  group_by(year, month) %>% 
  mutate(month_diff_max_min = mean(diff_max_min)) %>%  
  ungroup() %>% 
  select(year, month, month_diff_max_min) %>% 
  unique() %>% 
  arrange(year, month) %>% 
  mutate(type = ifelse(month == "05", "Highlighted", "Normal")
         ) %>% 
  ggplot(
    aes(
      x = month,
      y = month_diff_max_min,
      fill = type,
      alpha = type
    ))+
  geom_boxplot() + 
  scale_fill_manual(values=c("brown1", "white")) +
  scale_alpha_manual(values=c(1,0.1)) +
  theme(legend.position = "none") +
  theme_classic() +
  labs(
    title = "Average Temperature Difference across Month in New York",
    x = "Month",
    y = "Temperature Difference",
    caption = "Data from the rnoaa package") +
  theme(legend.position = "none")

ggplotly(boxplot_diff)


```

### Chart C

```{r, echo = FALSE, warning = FALSE}
p = 
nydat %>%
  filter(id %in% c("USC00300331", "USC00300785","USC00304174")) %>% 
  mutate(year = year(date),
         month = month(date, label = TRUE),
         day = day(date)) %>% 
  filter(year == 2010) %>% 
  group_by(id) %>% 
  arrange(date) %>% 
  ggplot(
    aes(
      x = tmin,
      y = tmax,
      size = prcp,
      color = id
    ))+
  geom_point(alpha = 0.7) +
  scale_size(range = c(2,12))+
  theme_bw() + 
  ggtitle("Visulization of maximum temperature, minimum tempature and precipitation") +
  labs(
    title = "Date: {frame_time}",
    x = "Minimum temperature",
    y = "Maximum temperature") +
  transition_time(date) + 
  ease_aes("linear", interval = 0.001)+
  shadow_mark(alpha = 0.3, size = 0.5)

animate(p, fps = 1, duration = 300)

```

