---
title: "plotly"
output: html_document
code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(viridis)
library(p8105.datasets)
library(plotly)
library(tidyverse)
library(rnoaa)
library(dplyr)
library(lubridate)
library(gganimate)
library(gifski)
library(p8105.datasets)
library(fmsb)
library(RColorBrewer)
library(scales)
data("nyc_airbnb")
data("instacart")
data("rest_inspec")

```


```{r, include=FALSE}
#data cleaning
set.seed(1)

data(nyc_airbnb)
nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(rating = review_scores_location / 2) %>%
  select(
    neighbourhood_group, neighbourhood, rating, price, room_type, lat, long) %>%
  filter(
    !is.na(rating), 
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500)  %>% 
  sample_n(5000)
```

```{r, echo=FALSE, warning = FALSE, include = FALSE}
nyc_airbnb %>% 
  plot_ly(x = ~lat, y = ~long, type = "scatter", mode = "markers",
    color = ~price, alpha = 0.5)
```

```{r, echo=FALSE, warning = FALSE, include = FALSE}
nyc_airbnb %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  plot_ly(y = ~price, color = ~neighbourhood, type = "box", colors = "Set2")
```

```{r, echo = FALSE, warning = FALSE, include = FALSE}
nyc_airbnb %>% 
  count(neighbourhood) %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar", colors = "YlGnBu")
```

## Instacart Data Visualization
```{r, echo = FALSE, warning = FALSE, message = FALSE}

instacart %>% 
  group_by(department, order_dow) %>% 
  summarize(count_week = n()) %>%
  ungroup() %>% 
  group_by(department) %>% 
  mutate(prct_week = 100*count_week/sum(count_week)) %>%
  ungroup() %>% 
  mutate(alcohol_flag = ifelse(department == "alcohol", "alcohol", "non-alcohol")) %>% 
  group_by(department) %>% 
  plot_ly(x = ~order_dow, 
          y = ~prct_week, 
          color = ~alcohol_flag,
          type = "scatter",
          mode = "lines+markers",
          line = list(shape = "spline", width = 2),
          marker = list(symbol = "star-diamond",size = 2),
          alpha = 0.7,
          colors = c("red","grey")
          )   %>% 
  layout(
    title = "Alcohol's selling trend comparing to other commodities",
    xaxis = list(
      title = "Order Day of the Week"
    ),
    yaxis = list(
      title = "Percentage (%)",
      zeroline = F
    ),
    legend = list(
      orientation = "bottom"
    )
  )
```

```{r, echo = FALSE, warning = FALSE}
instacart %>%
  filter(department == "alcohol" | department == "dairy eggs") %>% 
  group_by(order_hour_of_day, aisle) %>% 
  mutate(aisle_n = n()) %>%
  select(department, order_hour_of_day, aisle, aisle_n) %>% 
  unique() %>% 
  arrange(aisle, order_hour_of_day) %>% 
  ungroup() %>% 
  group_by(aisle) %>% 
  mutate(aisle_pctn = 100*aisle_n/sum(aisle_n)) %>%
  plot_ly(
    x = ~order_hour_of_day,
    y = ~aisle_pctn,
    alpha = 0.9,
    color = ~department,
    type = "scatter",
    mode = "markers",
    marker = list(symbol = "star-diamond",size = 5),
    colors = c("red", "blue")
  )  %>% 
  layout(
    title = "The distribution of selling percentage across order hour of a day",
    xaxis = list(
      title = "Order Hour of the Day"
    ),
    yaxis = list(
      title = "Percentage (%)",
      zeroline = F
    ),
    legend = list(
      orientation = "bottom"
    )
  )


```


```{r, echo = FALSE, warning = FALSE}
top_5_alcohol = 
  instacart%>% 
  filter(department == "alcohol") %>% 
  group_by(product_id) %>% 
  mutate(total_n = sum(n())) %>% 
  select(product_id, product_name, total_n) %>% 
  unique() %>% 
  arrange(desc(total_n)) %>% 
  head(6)

instacart %>% 
  filter(product_id %in% c(top_5_alcohol$product_id)) %>% 
  group_by(product_id, order_dow) %>% 
  mutate(n_daily_product = n()) %>% 
  select(product_id, product_name, order_dow, n_daily_product, department, aisle) %>% 
  unique() %>% 
  ungroup() %>%
  mutate(product_name = fct_relevel(product_name, c("Beer", "Cabernet Sauvignon", "Chardonnay", "India Pale Ale","Sauvignon Blanc","Vodka"))) %>% 
  group_by(product_id) %>% 
  arrange(product_name, order_dow) %>% 
  plot_ly(
    x = ~order_dow,
    y = ~n_daily_product,
    type = "scatter",
    mode = "lines+markers",
    color = ~product_name,
    text = ~product_name,
    alpha = 0.8,
    line = list(shape = 'spline', width= 2.3),
    marker = list(symbol = "star-diamond",size = 5),
    colors = c("cornflowerblue","lightblue","lightsteelblue","lightsteelblue2", "indianred4", "brown")
  )  %>% 
  layout(
    title = "Different ordering pattern for different alcohol products",
    xaxis = list(
      title = "Order Day of the week",
      zeroline = F
    ),
    yaxis = list(
      title = "Frequency",
      zeroline = F
    )
  )

```



```{r, echo = FALSE, warning = FALSE}
top_50_icecream = 
  instacart %>% 
  filter(aisle == "ice cream ice") %>% 
  group_by(product_id) %>% 
  mutate(total_n_product = n()) %>% 
  select(product_id, product_name, total_n_product) %>% 
  arrange(desc(total_n_product)) %>% 
  unique() %>% 
  head(50)

bar_icecream = 
  instacart %>%
  filter(product_name %in% top_50_icecream$product_name) %>% 
  count(product_name) %>% 
  mutate(
    product_name = fct_reorder(product_name, n)
  ) %>%
  ggplot(
    aes(
      x = product_name,
      y = n
    )
  )+
  geom_bar(
    stat = "identity",
    fill = "cornflowerblue",
    alpha = .7,
    width = .7
  )+
  coord_flip()+
  theme_bw()+
  xlab("")+
  ylab("")+
  ggtitle("The 50 best selling icecream")
  
ggplotly(bar_icecream)  
  
  

```


## NOAA Data Visualization

```{r, include = FALSE}

# Load the data
load("./nynoaadat.RData")

daily_tmin_tmax = 
  nydat %>% 
  mutate(date = as.character(date)) %>% 
  group_by(date) %>% 
  mutate(
    avg_tmax = mean(tmax, na.rm = TRUE),
    avg_tmin = mean(tmin, na.rm = TRUE)
    ) %>% 
  select(date, avg_tmax, avg_tmin) %>% 
  unique() %>%
  mutate(
    diff_max_min = avg_tmax - avg_tmin,
    month = substr(date, 6, 7),
    year = substr(date, 1, 4)
    )

```

```{r box_temp_diff, echo = FALSE, warning= FALSE}
boxplot_diff = 
  daily_tmin_tmax %>% 
  group_by(year, month) %>% 
  mutate(month_diff_max_min = mean(diff_max_min)) %>%  
  ungroup() %>% 
  select(year, month, month_diff_max_min) %>% 
  unique() %>% 
  arrange(year, month) %>% 
  mutate(type = ifelse(month == "05", "Highlighted", "Normal")
         ) %>% 
  ggplot(
    aes(
      x = month,
      y = month_diff_max_min,
      fill = type,
      alpha = type
    ))+
  geom_boxplot() + 
  scale_fill_manual(values=c("brown1", "white")) +
  scale_alpha_manual(values=c(1,0.1)) +
  theme(legend.position = "none") +
  theme_classic() +
  labs(
    title = "Average Temperature Difference across Month in New York",
    x = "Month",
    y = "Temperature Difference",
    caption = "Data from the rnoaa package") +
  theme(legend.position = "none")

ggplotly(boxplot_diff)
```



```{r heat_max_temp, echo = FALSE, warning = FALSE, out.width="90%" }
heatmap_794 = 
  nydat %>% 
  filter(id == "USW00094794") %>% 
  mutate(year = year(date),
         month = month(date, label = TRUE),
         day = day(date)) %>% 
  filter(year %in% c(1986, 1996, 2006)) %>% 
  select(id, day, month, year, tmax) %>%
  ggplot(
    aes(
      x = month,
      y = day,
      fill = tmax
    )
  )+
  geom_tile(
    color = "white",
    size = 0.1
  )+
  ggtitle("The maximum temperature pattern in 1986, 1996, 2006")+
  scale_y_continuous(breaks =c(1,10,20,31))+
  scale_fill_viridis(name = "Maximum Temperature", option = "C")+
  facet_grid(~year)+
  labs( x="Month", y="Day Commencing")+ 
  theme(legend.position = "bottom")+
  theme(plot.title=element_text(size = 14))+
  theme(axis.text.y=element_text(size=6)) +
  theme(strip.background = element_rect(colour="white"))+
  theme(plot.title=element_text(hjust=0))+
  theme(axis.ticks=element_blank())+
  theme(axis.text=element_text(size=7))+
  theme(legend.title=element_text(size=8))+
  theme(legend.text=element_text(size=6))+
  theme_linedraw()

ggplotly(heatmap_794)

```

```{r, echo = FALSE, warning = FALSE}
p = 
nydat %>%
  filter(id %in% c("USC00300331", "USC00300785","USC00304174")) %>% 
  mutate(year = year(date),
         month = month(date, label = TRUE),
         day = day(date)) %>% 
  filter(year == 2010) %>% 
  group_by(id) %>% 
  arrange(date) %>% 
  ggplot(
    aes(
      x = tmin,
      y = tmax,
      size = prcp,
      color = id
    ))+
  geom_point(alpha = 0.7) +
  scale_size(range = c(2,12))+
  theme_bw() + 
  ggtitle("Visulization of maximum temperature, minimum tempature and precipitation") +
  labs(
    title = "Date: {frame_time}",
    x = "Minimum temperature",
    y = "Maximum temperature") +
  transition_time(date) + 
  ease_aes("linear", interval = 0.001)+
  shadow_mark(alpha = 0.3, size = 0.5)

animate(p, fps = 1, duration = 300)
```


```{r, include = FALSE}
latest_inspection = 
  rest_inspec %>%
  group_by(dba) %>% 
  arrange(desc(inspection_date)) %>% 
  top_n(1) %>% 
  select(boro, building, camis, cuisine_description, dba, inspection_date, score, grade) %>% 
  unique() %>% 
  filter(boro != "Missing") %>% 
  mutate(boro = fct_relevel(boro,
                       "MANHATTAN", "BRONX","STATEN ISLAND","QUEENS","BROOKLYN"))


```


```{r jitter_boxplot, echo = FALSE, warning = FALSE}
jitter_boxplot = 
  latest_inspection %>% 
  filter(cuisine_description == "Korean") %>% 
  ggplot(
    aes(
      x = boro,
      y = score,
      fill = boro
    )
  )+
  geom_boxplot()+
  scale_fill_viridis(discrete = TRUE, alpha = 0.6)+
  geom_jitter(color = "black", size = 0.4, alpha = 0.9) +
  theme_classic() +
  theme(
    legend.position = "none",
    plot.title = element_text(size = 11)
  ) +
  ggtitle("Korean Restuarant Score: A boxplot with jitter") +
  xlab("")

ggplotly(jitter_boxplot)
```

```{r, include = FALSE, warning = FALSE}
mean_score_cuisine = 
latest_inspection %>% 
  filter(cuisine_description %in% c("Korean", "French", "Greek", "Asian", "Indian", "Chinese", "American", "Mexican", "Japanese", "Bakery", "Spanish", "Thai")) %>% 
  group_by(boro, cuisine_description) %>% 
  mutate(
    n = n(),
    mean_score = mean(score, na.rm = TRUE)
  ) %>% 
  select(
    boro, cuisine_description, mean_score
  ) %>% 
  unique() %>% 
  arrange(boro, mean_score) %>% 
  ungroup() %>% 
  filter(boro != "Missing") %>% 
  mutate(boro = fct_relevel(boro,
                       "MANHATTAN", "BRONX","STATEN ISLAND","QUEENS","BROOKLYN"))

# Set a number of 'empty bar' to add at the end of each group
empty_bar = 3
to_add = data.frame( matrix(NA, empty_bar*nlevels(mean_score_cuisine$boro), ncol(mean_score_cuisine)) )
colnames(to_add) = colnames(mean_score_cuisine)
to_add$boro = rep(levels(mean_score_cuisine$boro), each=empty_bar)
mean_score_cuisine = rbind(mean_score_cuisine, to_add)
mean_score_cuisine = mean_score_cuisine %>% arrange(boro)
mean_score_cuisine$id = seq(1, nrow(mean_score_cuisine))

label_data = mean_score_cuisine
number_of_bar = nrow(label_data)
angle = 90 - 360 * (label_data$id-0.5) /number_of_bar     # I substract 0.5 because the letter must have the angle of the center of the bars. Not extreme right(1) or extreme left (0)
label_data$hjust = ifelse( angle < -90, 1, 0)
label_data$angle = ifelse(angle < -90, angle+180, angle)
 
# prepare a data frame for base lines
base_data =
  mean_score_cuisine %>% 
  group_by(boro) %>% 
  summarize(start=min(id), end=max(id) - empty_bar) %>% 
  rowwise() %>% 
  mutate(title=mean(c(start, end)))

```

```{r circular_bar, echo = FALSE, warning=FALSE}
# Make the plot

label_data %>% 
  ggplot(
    aes(
      x=as.factor(id), 
      y=mean_score, 
      fill=cuisine_description)
    ) +
  geom_bar(stat="identity", alpha=0.5) +
  ylim(-60,60) +
  theme_minimal() +
  theme(
    legend.position = "none",
    axis.text = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank(),
    plot.margin = unit(rep(-1,4), "cm") 
  ) +
  ggtitle("Average scoring of different rcuisine across different boro") +
  coord_polar() + 
  geom_text(data=label_data, aes(x=id, y=mean_score+10, label=paste(cuisine_description, ":", round(mean_score,1)), hjust=hjust), color="black", fontface="bold",alpha=0.6, size=2.5, angle= label_data$angle, inherit.aes = FALSE )+
   geom_segment(data=base_data, aes(x = start, y = -5, xend = end, yend = -5), colour = "black", alpha=0.8, size=0.6 , inherit.aes = FALSE )  +
  geom_text(data=base_data, aes(x = title, y = -15, label=boro), colour = "black", alpha=0.8, size=2, fontface="bold", inherit.aes = FALSE)
```

```{r, include = FALSE}
coul = brewer.pal(5, "Spectral")
colors_border = coul
colors_in = alpha(coul, 0.445)


radar_data = 
  latest_inspection %>% 
  group_by(cuisine_description, boro) %>% 
  mutate(mean_score = mean(score)) %>% 
  select(boro, cuisine_description, mean_score) %>% 
  filter(cuisine_description %in% c("Mexican", "Chinese", "Japanese", "Thai", "American")) %>% 
  unique() %>% 
  pivot_wider(
    names_from = "cuisine_description",
    values_from = "mean_score"
  )

radar_data = as.data.frame(radar_data)
rownames(radar_data) = radar_data$boro
radar_data = subset(radar_data, select = -c(boro))
radar_data = rbind(rep(20,5), rep(0,5), radar_data)

```

```{r radarchart, echo = FALSE}
radarchart(radar_data[-c(1,2),],
           axistype = 0,
           maxmin = F,
           pcol = colors_border,
           pfcol = colors_in,
           plwd = 2,
           plty = 1,
           cglcol = "grey",
           cglty = 1,
           axislabcol = "black",
           cglwd = 0.8,
           vlcex = 0.8,
           title = "Comparison of inspection score in difference cuisine in different boro") 
legend(x = 1, y = 1.3, legend = rownames(radar_data[-c(1,2),]), col = colors_in, pch = 20, cex = 0.7, pt.cex = 1, bty = "n")


```





